class SymptomMapper {
  static final Map<String, RegExp> _symptomPatterns = {
    'high_temperature': RegExp(
        r'حرارة عالية|حمى|سخونة|حرارة|حراره|الحرارة|high temperature|fever|heat'),
    'cough': RegExp(r'سعال|كحة'),
    'sore_throat': RegExp(r'التهاب حلق|احتقان الحلق|ألم في الحلق'),
    'muscle_pain': RegExp(r'ألم عضلي|وجع عضلات'),
    'fatigue': RegExp(r'عب شديد|إعياء|التعب|تعب'),
    'exhaustion': RegExp(r'إجهاد|إنهاك|ارهاق|أرهاق|تعب مفرط'),
    'headache': RegExp(r'صداع|ألم في الرأس'),
    'increased_thirst': RegExp(r'عطش زائد|زيادة العطش|العطش'),
    'weight_loss': RegExp(r'فقدان وزن|نقصان في الوزن|فقدان الوزن'),
    'blurred_vision':
        RegExp(r'رؤية ضبابية|تشوش في الرؤية|تشوش الرؤية|تشوش الرؤيه'),
    'dizziness': RegExp(r'دوخة|دوار'),
    'nosebleed': RegExp(r'نزيف أنفي|رعاف|نزيف انفي'),
    'shortness_of_breath': RegExp(r'ضيق تنفس|صعوبة في التنفس'),
    'difficulty_breathing': RegExp(r'صعوبة التنفس|تنفس مجهد'),
    'wheezing': RegExp(r'صفير عند التنفس|أزيز'),
    'chest_tightness': RegExp(r'ضيق في الصدر|شد بالصدر'),
    'persistent_sadness': RegExp(r'حزن مستمر|كآبة'),
    'loss_of_interest': RegExp(r'فقدان الاهتمام|عدم مبالاة'),
    'insomnia': RegExp(r'أرق|صعوبة في النوم'),
    'hypersomnia': RegExp(r'فرط النوم|النوم المفرط'),
    'appetite_changes': RegExp(r'تغير في الشهية|زيادة أو نقصان في الأكل'),
    'weight_changes': RegExp(r'تغيرات في الوزن|زيادة أو نقصان الوزن'),
    'difficulty_concentrating': RegExp(r'صعوبة في التركيز|تشتت الانتباه'),
    'joint_pain': RegExp(r'ألم في المفاصل|وجع مفصل'),
    'joint_swelling': RegExp(r'تورم المفاصل|انتفاخ مفصل'),
    'joint_stiffness': RegExp(r'تصلب المفاصل|تيبس المفصل'),
    'joint_redness': RegExp(r'احمرار المفاصل|احمرار في المفصل'),
    'joint_warmth': RegExp(r'سخونة المفاصل|حرارة في المفصل'),
    'chest_pain': RegExp(r'ألم في الصدر|وجع الصدر'),
    'chest_pressure': RegExp(r'ضغط في الصدر|ثقل في الصدر'),
    'heart_palpitations': RegExp(r'خفقان القلب|تسارع نبضات القلب'),
    'memory_loss': RegExp(r'فقدان الذاكرة|ضعف الذاكرة'),
    'difficulty_thinking': RegExp(r'صعوبة في التفكير|تشوش ذهني'),
    'problem_solving_difficulty':
        RegExp(r'صعوبة في حل المشكلات|عجز عن إيجاد حلول'),
    'mood_changes': RegExp(r'تغيرات مزاجية|تقلب المزاج'),
    'behavioral_changes': RegExp(r'تغيرات في السلوك|سلوك غير معتاد'),
    'difficulty_performing_tasks':
        RegExp(r'صعوبة في أداء المهام|عدم القدرة على إتمام الأعمال'),
    'loss_of_appetite': RegExp(r'فقدان الشهية|انعدام الرغبة في الأكل'),
    'nausea': RegExp(r'غثيان|شعور بالتقيؤ'),
    'vomiting': RegExp(r'تقيؤ|استفراغ'),
    'yellow_skin': RegExp(r'اصفرار الجلد'),
    'yellow_eyes': RegExp(r'اصفرار العينين'),
    'jaundice': RegExp(r'يرقان|صفار'),
    'sneezing': RegExp(r'عطس|العطاس'),
    'runny_nose': RegExp(r'سيلان الأنف|أنف يسيل'),
    'itchy_eyes': RegExp(r'حكة في العين|عيون تحك'),
    'skin_itching': RegExp(r'حكة جلدية|هرش الجلد'),
    'skin_rash': RegExp(r'طفح جلدي|احمرار الجلد'),
    'persistent_cough': RegExp(r'سعال مستمر|كحة مزمنة'),
    'fever': RegExp(r'حمى|ارتفاع درجة الحرارة'),
    'abdominal_pain': RegExp(r'ألم بطني|وجع في البطن'),
    'burning_sensation': RegExp(r'إحساس بالحرقان|حرقة'),
    'chronic_diarrhea': RegExp(r'إسهال مزمن|إسهال مستمر'),
    'bloody_diarrhea': RegExp(r'إسهال دموي|دم في الإسهال'),
    'severe_back_pain': RegExp(r'ألم شديد في الظهر|وجع ظهر قوي'),
    'lower_back_pain': RegExp(r'ألم أسفل الظهر|وجع في المنطقة القطنية'),
    'blood_in_urine': RegExp(r'دم في البول|تبول دموي'),
    'frequent_urination': RegExp(r'تبول متكرر|كثرة التبول|التبول'),
    'painful_urination': RegExp(r'تبول مؤلم|حرقة أثناء التبول'),
    'cloudy_urine': RegExp(r'بول عكر|بول غير صافي'),
    'foul_smelling_urine': RegExp(r'رائحة كريهة للبول|بول ذو رائحة قوية'),
    'weakness': RegExp(r'ضعف عام|وهن'),
    'pale_skin': RegExp(r'شحوب الجلد|بشرة باهتة'),
    'recurrent_fever': RegExp(r'حمى متكررة|ارتفاع حرارة متكرر'),
    'night_sweats': RegExp(r'تعرق ليلي|العرق أثناء النوم'),
    'hand_tremor': RegExp(r'رعشة في اليد|اهتزاز اليد'),
    'movement_difficulty': RegExp(r'صعوبة في الحركة|عجز عن التنقل'),
    'muscle_stiffness': RegExp(r'تصلب العضلات|تيبس عضلي'),
    'muscle_weakness': RegExp(r'ضعف عضلي|قوة عضلية منخفضة'),
    'numbness': RegExp(r'خدر|تنميل'),
    'tingling': RegExp(r'وخز|نخز'),
    'balance_difficulty': RegExp(r'فقدان التوازن|صعوبة في التوازن'),
    'ear_pain': RegExp(r'ألم في الأذن|وجع الأذن'),
    'hearing_loss': RegExp(r'ضعف السمع|فقدان السمع'),
    'ear_discharge': RegExp(r'إفرازات من الأذن|سيلان الأذن'),
    'rapid_weight_loss': RegExp(r'فقدان وزن سريع|نزول وزن مفاجئ'),
    'weight_gain': RegExp(r'زيادة في الوزن|ارتفاع الوزن'),
    'feeling_cold': RegExp(r'الشعور بالبرد|إحساس دائم بالبرودة'),
    'dry_skin': RegExp(r'جفاف الجلد|بشرة جافة'),
    'increased_appetite': RegExp(r'زيادة الشهية|رغبة زائدة في الأكل'),
    'rapid_heartbeat': RegExp(r'تسارع ضربات القلب|نبض سريع'),
    'persistent_fatigue': RegExp(r'إرهاق دائم|تعب مستمر'),
    'swollen_lymph_nodes': RegExp(r'تورم الغدد اللمفاوية|عقد لمفاوية متضخمة'),
    'facial_weakness': RegExp(r'ضعف في عضلات الوجه|شلل وجهي جزئي'),
    'arm_weakness': RegExp(r'ضعف في الذراع|وهن الذراع'),
    'leg_weakness': RegExp(r'ضعف في الساق|وهن في الرجل'),
    'speech_difficulty': RegExp(r'صعوبة في الكلام|اضطراب في النطق'),
    'loss_of_balance': RegExp(r'فقدان التوازن|خلل في التوازن'),
    'severe_itching': RegExp(r'حكة شديدة|هرش قوي'),
    'skin_redness': RegExp(r'احمرار الجلد|احمرار البشرة'),
    'skin_patches': RegExp(r'بقع جلدية|تصبغات على الجلد'),
    'severe_headache': RegExp(r'صداع شديد|ألم رأس قوي'),
    'light_sensitivity': RegExp(r'حساسية من الضوء|انزعاج من الإضاءة'),
    'sound_sensitivity': RegExp(r'حساسية من الأصوات|انزعاج من الضجيج'),
    'diarrhea': RegExp(r'إسهال|إسهال مستمر'),
    'painful_swallowing': RegExp(r'ألم عند البلع|بلع مؤلم'),
    'tonsil_redness': RegExp(r'احمرار اللوزتين|التهاب اللوزتين'),
    'tonsil_swelling': RegExp(r'تورم اللوزتين|انتفاخ اللوز'),
    'skin_blisters': RegExp(r'بثور جلدية|فقاعات جلدية'),
    'constant_anxiety': RegExp(r'قلق دائم|توتر مستمر'),
    'tension': RegExp(r'توتر|شد عصبي'),
    'increased_heartbeat': RegExp(r'زيادة ضربات القلب|خفقان سريع'),
    'attention_difficulty': RegExp(r'صعوبة في التركيز|ضعف الانتباه'),
    'impulsivity': RegExp(r'اندفاعية|تصرفات متهورة'),
    'hyperactivity': RegExp(r'فرط النشاط|نشاط زائد'),
    'joint_area_swelling': RegExp(r'تورم في المفصل|انتفاخ حول المفصل'),
    'skin_itch': RegExp(r'حكة في الجلد|هرش جلدي'),
    'painless_genital_sores':
        RegExp(r'تقرحات تناسلية غير مؤلمة|جروح في الأعضاء التناسلية دون ألم'),
    'painless_mouth_sores':
        RegExp(r'تقرحات فموية غير مؤلمة|جروح في الفم بدون ألم'),
    'joint_fever': RegExp(r'حمى المفاصل|سخونة في المفاصل'),
    'heart_inflammation': RegExp(r'التهاب القلب|التهاب عضلة القلب'),
    'blood_vessel_inflammation':
        RegExp(r'التهاب الأوعية الدموية|التهاب شرايين'),
  };

  // 2. دالة التحويل الرئيسية
  static String convertTextToSymptom(String text) {
    final lowerText = text.toLowerCase();

    // 3. البحث في الأنماط حسب الأولوية
    for (final entry in _symptomPatterns.entries) {
      if (entry.value.hasMatch(lowerText)) {
        return entry.key;
      }
    }

    return ''; // إذا لم يوجد تطابق
  }
}