name: disease_discovery_project
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.5
  equatable: ^2.0.5
  # google_ml_kit: ^0.19.0
  flutter_tts: ^4.2.2
  # flutter_tts: ^3.8.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  lottie: ^3.1.0
  tflite_flutter: ^0.11.0
  # tflite_flutter_helper: ^0.3.1
  # tflite_flutter_plus: ^0.0.1
  # path_provider: ^2.1.5

  cupertino_icons: ^1.0.8
  # استخدام أيقونات iOS-style مثل أيقونات النظام في أجهزة Apple.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  #  مجموعة من قواعد الفحص (linting rules) التي تساعدك في تحسين جودة الكود، واكتشاف الأخطاء، واتباع أفضل ممارسات البرمجة

flutter_launcher_icons:
  android: "launcher_icon"
  ios:
    true
    # command => flutter pub run flutter_launcher_icons
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  # command => flutter pub run flutter_native_splash:create
  background_image: "assets/images/native_splash.png"
  # android_gravity: fill

  # change app name : 1- go to android/app/src/main/AndroidManifest.xml
  #                   2- change the name from android:label="disease_discovery_project" to android:label="Disease Discovery"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/animation/
    - assets/app.py
    - assets/disease_model.tflite
    - assets/labels.json
