class SymptomMapper {
  static final Map<String, RegExp> _symptomPatterns = {
    'itching': RegExp(r'حكه|هرش|حَكَّة|حكّة'),
    'skin_rash': RegExp(r'طفح جلدي|بقع جلد|احمرار الجلد'),
    'nodal_skin_eruptions': RegExp(r'تقرحات جلد|انتفاخات جلد'),
    'continuous_sneezing': RegExp(r'عطس متواصل|عطاس مستمر'),
    'shivering': RegExp(r'رعشة|ارتجاف'),
    'chills': RegExp(r'قشعريرة|برد مفاجئ'),
    'joint_pain': RegExp(r'الم مفاصل|تيبس المفاصل'),
    'stomach_pain': RegExp(r'الم معدة|الم المعده|وجع بطن'),
    'acidity': RegExp(r'حموضه|حرقة معدة'),
    'ulcers_on_tongue': RegExp(r'تقرحات لسان|قروح لسان'),
    'muscle_wasting': RegExp(r'ضمور عضلات|هزال عضلي'),
    'vomiting': RegExp(r'ترجيع|استفراغ'),
    'burning_micturition': RegExp(r'حرقان بول|الم عند التبول'),
    'spotting_urination': RegExp(r'نزول دم مع البول|بقع بول'),
    'fatigue': RegExp(r'تعب|إرهاق'),
    'weight_gain': RegExp(r'زيادة وزن|سمنة مفاجئة'),
    'anxiety': RegExp(r'قلق|توتر'),
    'cold_hands_and_feets': RegExp(r'برودة أطراف|يدين وقدمين باردة'),
    'mood_swings': RegExp(r'تقلبات مزاج|تغيير المزاج'),
    'weight_loss': RegExp(r'فقدان وزن|نقص وزن'),
    'restlessness': RegExp(r'تململ|عدم راحة'),
    'lethargy': RegExp(r'خمول|كسل'),
    'patches_in_throat': RegExp(r'بقع في الحلق|رقع بلعوم'),
    'irregular_sugar_level': RegExp(r'سكر غير منتظم|تذبذب سكر الدم'),
    'cough': RegExp(r'سعال|كحه|كحة'),
    'high_fever': RegExp(r'حمى شديدة|سخونة عالية'),
    'sunken_eyes': RegExp(r'عيون غائرة|انخفاض العيون'),
    'breathlessness': RegExp(r'ضيق تنفس|اختناق'),
    'sweating': RegExp(r'تعرق|إفراز عرق'),
    'dehydration': RegExp(r'جفاف|قلة سوائل'),
    'indigestion': RegExp(r'عسر هضم|صعوبة هضم'),
    'headache': RegExp(r'صداع|الم راس'),
    'pain_behind_the_eyes': RegExp(r'الم خلف العين|وجع وراء العيون'),
    'yellowish_skin': RegExp(r'اصفرار الجلد|يبوسة الجلد'),
    'dark_urine': RegExp(r'بول داكن|لون بول غامق'),
    'nausea': RegExp(r'غثيان|دوخة'),
    'loss_of_appetite': RegExp(r'فقدان شهية|عدم رغبة بالأكل'),
    'constipation': RegExp(r'امساك|صعوبة إخراج'),
    'diarrhoea': RegExp(r'اسهال|إسهال'),
    'abdominal_pain': RegExp(r'الم بطن|وجع معدة'),
    'mild_fever': RegExp(r'حمى خفيفة|سخونة بسيطة'),
    'yellow_urine': RegExp(r'بول أصفر|لون بول فاتح'),
    'yellowing_of_eyes': RegExp(r'اصفرار العين|بياض عين مصفر'),
    'acute_liver_failure': RegExp(r'فشل كبدي|توقف الكبد'),
    'fluid_overload': RegExp(r'احتباس سوائل|زيادة السوائل'),
    'swelling_of_stomach': RegExp(r'تورم البطن|انتفاخ المعدة'),
    'swelled_lymph_nodes':
        RegExp(r'تضخم الغدد الليمفاوية|انتفاخ العقد اللمفاوية'),
    'malaise': RegExp(r'توعك|إرهاق عام'),
    'blurred_and_distorted_vision': RegExp(r'زغللة|رؤية مشوشة'),
    'phlegm': RegExp(r'بلغم|مخاط'),
    'throat_irritation': RegExp(r'تهيج الحلق|حكة الحلق'),
    'redness_of_eyes': RegExp(r'احمرار العين|عيون محتقنة'),
    'sinus_pressure': RegExp(r'ضغط الجيوب الأنفية|ألم الجيوب'),
    'runny_nose': RegExp(r'سيلان الأنف|رشح'),
    'congestion': RegExp(r'احتقان|انسداد الأنف'),
    'chest_pain': RegExp(r'ألم صدر|ضيق في الصدر'),
    'weakness_in_limbs': RegExp(r'ضعف في الأطراف|وهن في الأرجل'),
    'fast_heart_rate': RegExp(r'سرعة نبضات القلب|خفقان'),
    'pain_during_bowel_movements': RegExp(r'ألم أثناء التبرز|وجع عند الإخراج'),
    'pain_in_anal_region': RegExp(r'ألم شرجي|حرقان في فتحة الشرج'),
    'bloody_stool': RegExp(r'براز دموي|دم في البراز'),
    'irritation_in_anus': RegExp(r'تهيج شرجي|حكة في الشرج'),
    'neck_pain': RegExp(r'ألم رقبة|تيبس الرقبة'),
    'dizziness': RegExp(r'دوخة|إحساس بالدوران'),
    'cramps': RegExp(r'تشنجات|تقلصات عضلية'),
    'bruising': RegExp(r'كدمات|بقع زرقاء'),
    'obesity': RegExp(r'سمنة|زيادة وزن مفرطة'),
    'swollen_legs': RegExp(r'تورم الساقين|قدمين متورمتين'),
    'swollen_blood_vessels': RegExp(r'تورم الأوعية الدموية|عروق منتفخة'),
    'swollen_extremeties': RegExp(r'تورم الأطراف|انتفاخ اليدين والقدمين'),
    'puffy_face_and_eyes': RegExp(r'تورم الوجه|انتفاخ الوجه|وجه منتفخ'),
    'enlarged_thyroid': RegExp(r'تضخم الغدة الدرقية|كبر حجم الدرقية'),
    'brittle_nails': RegExp(r'هشاشة أظافر|تقصف الأظافر'),
    'excessive_hunger': RegExp(r'جوع شديد|شراهة في الأكل'),
    'extra_marital_contacts': RegExp(r'علاقات جنسية خطرة|اتصالات غير شرعية'),
    'drying_and_tingling_lips': RegExp(r'جفاف الشفاه|وخز في الشفاه'),
    'slurred_speech': RegExp(r'ثقل في اللسان|كلام متداخل'),
    'knee_pain': RegExp(r'ألم ركبة|وجع ركبة'),
    'hip_joint_pain': RegExp(r'ألم ورك|وجع مفصل الفخذ'),
    'muscle_weakness': RegExp(r'ضعف عضلات|وهن عضلي'),
    'stiff_neck': RegExp(r'تيبس الرقبة|صلابة الرقبة'),
    'swelling_joints': RegExp(r'تورم المفاصل|انتفاخ المفاصل'),
    'movement_stiffness': RegExp(r'تيبس الحركة|صعوبة في الحركة'),
    'spinning_movements': RegExp(r'دوار|شعور بالدوران'),
    'loss_of_balance': RegExp(r'فقدان التوازن|عدم اتزان'),
    'unsteadiness': RegExp(r'ترنح|عدم ثبات'),
    'weakness_of_one_body_side': RegExp(r'ضعف في جانب واحد|شلل نصفي'),
    'loss_of_smell': RegExp(r'فقدان الشم|عدم تمييز الروائح'),
    'bladder_discomfort': RegExp(r'ألم مثانة|حرقة في المثانة'),
    'foul_smell_of urine': RegExp(r'رائحة بول كريهة|بول نتن'),
    'continuous_feel_of_urine':
        RegExp(r'رغبة مستمرة في التبول|شعور دائم بالتبول'),
    'passage_of_gases': RegExp(r'غازات|انتفاخ البطن'),
    'belly_pain': RegExp(r'الم بطن|انتفاخ البطن'),
    'depression': RegExp(r'اكتئاب|حزن شديد'),
    'irritability': RegExp(r'تهيج|نرفزة'),
    'altered_sensorium': RegExp(r'تغير في الوعي|اضطراب إدراكي'),
    'red_spots_over_body': RegExp(r'بقع حمراء على الجلد|طفح جلدي أحمر'),
    'lack_of_concentration': RegExp(r'صعوبة تركيز|شرود ذهني'),
    'visual_disturbances': RegExp(r'اضطرابات بصرية|زغللة في العين'),
    'mucoid_sputum': RegExp(r'بلغم مخاطي|إفرازات لزجة'),
    'rusty_sputum': RegExp(r'بلغم بني|بلغم صدئ'),
    'blood_in_sputum': RegExp(r'دم في البلغم|نفث الدم'),
    'muscle_pain': RegExp(r'الم عضلات|وجع عضلي'),
    'palpitations': RegExp(r'خفقان|سرعة نبض|شعور بالنبض'),
    'pus_filled_pimples': RegExp(r'بثور صديدية|حبوب مليئة بالصديد'),
    'blackheads': RegExp(r'رؤوس سوداء|كوميدونات'),
    'scurring': RegExp(r'ندبات|آثار جلدية'),
    'skin_peeling': RegExp(r'تقشير الجلد|تساقط الجلد'),
    'silver_like_dusting': RegExp(r'غبار فضي|طبقة فضية على الجلد'),
    'small_dents_in_nails': RegExp(r'نقرات في الأظافر|حفر صغيرة في الأظافر'),
    'inflammatory_nails': RegExp(r'التهاب الأظافر|احمرار حول الأظافر'),
    'watering_from_eyes': RegExp(r'دماع العيون|تدميع'),
    'increased_appetite': RegExp(r'زيادة الشهية|جوع مفرط'),
    'polyuria': RegExp(r'تبول متكرر|كثرة التبول'),
    'toxic_look_(typhos)': RegExp(r'مظهر سام|علامات تيفوئيد'),
    'abnormal_menstruation': RegExp(r'اضطراب الدورة الشهرية|نزيف غير طبيعي'),
    'dischromic _patches': RegExp(r'بقع جلدية ملونة|تصبغات جلدية'),
    'family_history': RegExp(r'تاريخ عائلي مرضي|أمراض وراثية'),
    'painful_walking': RegExp(r'ألم عند المشي|صعوبة في المشي'),
    'receiving_blood_transfusion': RegExp(r'نقل دم|تلقى دم'),
    'receiving_unsterile_injections': RegExp(r'حقن غير معقمة|إبر ملوثة'),
    'coma': RegExp(r'غيبوبة|فقدان الوعي'),
    'stomach_bleeding': RegExp(r'نزيف معدي|نزيف في المعدة'),
    'distention_of_abdomen': RegExp(r'انتفاخ البطن|توسع البطن'),
    'history_of_alcohol_consumption': RegExp(r'تاريخ مع الكحول|إدمان كحول'),
    'prominent_veins_on_calf': RegExp(r'أوردة بارزة في الساق|عروق ظاهرة'),
    'blister': RegExp(r'نفطات|فقاعات جلدية'),
    'red_sore_around_nose': RegExp(r'احمرار حول الأنف|التهاب حول الأنف'),
    'yellow_crust_ooze': RegExp(r'قشور صفراء|إفرازات صفراء'),
    'back_pain': RegExp(r'ألم ظهر|وجع في الظهر'),
    'internal_itching': RegExp(r'حكة داخلية|هرش داخلي'),
  };

  // 2. دالة التحويل الرئيسية
  static String convertTextToSymptom(String text) {
    final lowerText = text.toLowerCase();

    // 3. البحث في الأنماط حسب الأولوية
    for (final entry in _symptomPatterns.entries) {
      if (entry.value.hasMatch(lowerText)) {
        return entry.key;
      }
    }

    return ''; // إذا لم يوجد تطابق
  }
}
