Map<String, List<String>> allCountries = {
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Taif",
    "Tabuk",
    "Abha",
    "Hail",
    "Najran",
    "Jizan",
    "Al Bahah",
    "Sakakah",
    "Arar"
  ],
  "Egypt": [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "Mansoura",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Faiyum",
    "Zagazig"
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Al Ain",
    "Ras Al Khaimah",
    "Fujairah",
    "Ajman",
    "Umm Al Quwain"
  ],
  "Morocco": [
    "Rabat",
    "Casablanca",
    "Marrakech",
    "Fes",
    "Tangier",
    "Agadir",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "El Jadida",
    "Nador"
  ],
  "Algeria": [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Djelfa",
    "Setif",
    "Sidi Bel Abbes",
    "Biskra",
    "Tebessa",
    "Bejaia",
    "Tlemcen"
  ],
  "Tunisia": [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Bizerte",
    "Gabes",
    "Ariana",
    "Gafsa",
    "Monastir",
    "Nabeul",
    "Tataouine",
    "Tozeur"
  ],
  "Iraq": [
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Kirkuk",
    "Najaf",
    "Karbala",
    "Sulaymaniyah",
    "Nasiriyah",
    "Diwaniyah",
    "Samawah",
    "Kut",
    "Hilla"
  ],
  "Yemen": [
    "Sana'a",
    "Aden",
    "Taiz",
    "Al Hudaydah",
    "Ibb",
    "Mukalla",
    "Dhamar",
    "Amran",
    "Sayun",
    "Zinjibar",
    "Lahij",
    "Marib"
  ],
  "Syria": [
    "Damascus",
    "Aleppo",
    "Homs",
    "Latakia",
    "Hama",
    "Deir ez-Zor",
    "Raqqa",
    "Tartus",
    "Hasakah",
    "Qamishli",
    "Daraa",
    "Suwayda"
  ],
  "Lebanon": [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Zahle",
    "Jounieh",
    "Tyre",
    "Baabda",
    "Batroun",
    "Baalbek",
    "Byblos"
  ],
  "Palestine": [
    "Jerusalem",
    "Gaza",
    "Ramallah",
    "Nablus",
    "Hebron",
    "Bethlehem",
    "Jenin",
    "Tulkarm",
    "Qalqilya"
  ],
  "Jordan": [
    "Amman",
    "Zarqa",
    "Irbid",
    "Aqaba",
    "Madaba",
    "Salt",
    "Mafraq",
    "Jerash",
    "Karak",
    "Tafila"
  ],
  "Libya": [
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Zawiya",
    "Bayda",
    "Zliten",
    "Ajdabiya",
    "Sabha",
    "Derna",
    "Tobruk"
  ],
  "Sudan": [
    "Khartoum",
    "Omdurman",
    "Port Sudan",
    "Kassala",
    "El Obeid",
    "Nyala",
    "Atbara",
    "Wad Madani"
  ],
  "Oman": [
    "Muscat",
    "Salalah",
    "Sohar",
    "Nizwa",
    "Sur",
    "Ibri",
    "Rustaq",
    "Khasab"
  ],
  "Bahrain": ["Manama", "Muharraq", "Riffa", "Isa Town", "Hamad Town", "Sitra"],
  "Qatar": [
    "Doha",
    "Al Wakrah",
    "Al Khor",
    "Mesaieed",
    "Al Shahaniya",
    "Dukhan"
  ],
  "Kuwait": [
    "Kuwait City",
    "Hawalli",
    "Salmiya",
    "Jahra",
    "Farwaniya",
    "Fahaheel"
  ],
  "Mauritania": [
    "Nouakchott",
    "Nouadhibou",
    "Rosso",
    "Kiffa",
    "Kaédi",
    "Atar",
    "Zouerate"
  ]
};
